name: OpenAPI Test

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
      - run: cd packages/web3 && pnpm i
      # Wait for this issue to be resolved: https://github.com/acacode/swagger-typescript-api/issues/370
      - run: npm run update-schemas && test -z "$(git status --porcelain)"
      - run: npm run build
